name: Deploy PrivateBin securely
on:
  push:
    branches: ["main"]
jobs:
  tests:
    uses: rockeaters/PrivateBin/.github/workflows/tests.yml@main
  deploy:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Establish secure WireGuard session
        uses: NexRX/WireGuard-Session@v1
        with:
          wg-client-b64: ${{ secrets.WG_CONF_B64 }}
          timeout-address: ${{ secrets.SSH_HOST }}

      - name: Run deploy commands on remote server over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/privatebin/PrivateBin
            git pull origin main
            cd /opt/privatebin
            docker compose up -d
